[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self'"

[[headers]]
  for = "/index.html"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[redirects]] # Перенаправлення запитів до сервера на ваш власний сервер
from = "/api/*"
to = "http://localhost:9200/"
status = 200
force = true # Використовується для змусу перенаправлення
